
build_task:
  only_if: $CIRRUS_TAG != ''
  freebsd_instance:
    matrix:
      - image_family: freebsd-12-1-snap
      - image_family: freebsd-11-3-snap
  python_script: pkg install -y python3 python27 python35 python36 python37 python38
  ensurepip_script:
    - python2.7 -m ensurepip
    - python3.5 -m ensurepip
    - python3.6 -m ensurepip
    - python3.7 -m ensurepip
    - python3.8 -m ensurepip
  build_script: ./make-nix-release.sh
  archive_artifacts:
    path: "releases/*"
