name: "\U0001F4DA Documentation"
description: >-
  Did you find errors, problems, or anything unintelligible in the docs
  (https://python-poetry.org/docs)?
labels:
  - Documentation
  - Triage
body:
  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: >
        Hi there! Thank you for discovering and submitting an issue with our
        documentation.

        Please make sure the following boxes are ticked if they are correct.

        If not, please try and fulfill these first.
      options:
        - label: >-
            I have searched the
            [issues](https://github.com/python-poetry/poetry/issues) of this
            repo and believe that this is not a duplicate.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Now feel free to write your issue, but please be descriptive! Thanks again \U0001F64C ❤️\n"
    validations:
      required: true
