name: "\U0001F5C3 Everything Else"
description: >
  For questions and issues that do not fall in any of the other categories. This
  can include questions about Poetry's roadmap. For support questions, please
  post on StackOverflow.
body:
  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: Please confirm and check all the following options.
      options:
        - label: >-
            I have searched the
            [issues](https://github.com/python-poetry/poetry/issues) of this
            repo and believe that this is not a duplicate.
          required: true
        - label: >-
            I have searched the [documentation](https://python-poetry.org/docs/)
            and believe that my question is not covered.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Now feel free to write your issue, but please be descriptive! Thanks again \U0001F64C ❤️\n"
    validations:
      required: true
