name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: pipx run build

      - uses: actions/upload-artifact@v4
        with:
          name: distfiles
          path: dist/
          if-no-files-found: error

  upload-github:
    name: Upload (GitHub)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: distfiles

      - run: gh release upload ${{ github.event.release.tag_name }} dist/*.{tar.gz,whl}

  upload-pypi:
    name: Upload (PyPI)
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/poetry/
    permissions:
      id-token: write
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: distfiles

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
