name: Tests

on:
  push:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.changes.outputs.project }}
      fixtures-pypi: ${{ steps.changes.outputs.fixtures-pypi }}
      mypy: ${{ steps.changes.outputs.mypy }}
      pytest: ${{ steps.changes.outputs.pytest }}
      pytest-export: ${{ steps.changes.outputs.pytest-export }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            workflow: &workflow
              - '.github/workflows/tests.yaml'
              - '.github/workflows/.tests-matrix.yaml'
            project: &project
              - *workflow
              - 'poetry.lock'
              - 'pyproject.toml'
            fixtures-pypi:
              - *workflow
              - 'tests/repositories/fixtures/pypi.org/**'
            mypy:
              - *project
              - 'src/**.py'
            pytest:
              - *project
              - 'src/**.py'
              - 'tests/**'
            pytest-export:
              - *project
              - 'src/**.py'

  lockfile:
    name: Check poetry.lock
    runs-on: ubuntu-latest
    if: needs.changes.outputs.project == 'true'
    needs: changes
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/bootstrap-poetry

      - run: poetry check --lock

  fixtures-pypi:
    name: Check fixtures (PyPI)
    runs-on: ubuntu-latest
    if: needs.changes.outputs.fixtures-pypi == 'true'
    needs: changes
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/bootstrap-poetry

      - run: poetry install --sync --only main,test

      - run: poetry run env PYTHONPATH="$GITHUB_WORKSPACE" python tests/repositories/fixtures/pypi.org/generate.py

      - run: git diff --exit-code --stat HEAD tests/repositories/fixtures/pypi.org

  tests-matrix:
    name: ${{ matrix.os.name }} (Python ${{ matrix.python-version }})
    needs:
      - lockfile
      - changes
    strategy:
      matrix:
        os:
          - name: Ubuntu
            image: ubuntu-22.04
          - name: macOS
            image: macos-13
          - name: Windows
            image: windows-2022
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
      fail-fast: false
    # Use this matrix with multiple jobs defined in a reusable workflow:
    uses: ./.github/workflows/.tests-matrix.yaml
    with:
      runner: ${{ matrix.os.image }}
      python-version: ${{ matrix.python-version }}
      run-mypy: ${{ needs.changes.outputs.mypy == 'true' }}
      run-pytest: ${{ needs.changes.outputs.pytest == 'true' }}
      run-pytest-export: ${{ needs.changes.outputs.pytest-export == 'true' }}
    secrets: inherit

  status:
    name: Status
    runs-on: ubuntu-latest
    if: always()
    needs:
      - lockfile
      - fixtures-pypi
      - tests-matrix
    steps:
      - run: ${{ (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) && 'false' || 'true' }}
